### ISSUE TITLE
Add introduction on APT and ETC on the index page for APT/ETC

### ISSUE THREAD

**Issue by jwhite3** [spacetelescope/training-library#48]
It makes sense to give an introduction on what exactly APT and ETC are before diving down into the specifics of HST and JWST. I know that ETC is wildly different between HST and JWST, so I think naturally we'll have to explain that difference, but it should be super top-level. 

I've assigned all of you to this ticket since you all are working on the APT and ETC docs. This doesn't mean that one of you is responsible for it, but since you've all had a hand in updating these documents it makes sense for you to craft a brief introduction.

**Comment by dthatte** [comment]
I have the following text on the common index.html page on my branch.
"This module is meant as an introduction to ETC and APT used for designing an HST or
JWST science program.  The materials presented here will guide readers through the
step-by-step process of designing a science program using the ETC and APT."

How about we update it to the following:
This module is meant as an introduction to ETC and APT used for designing an HST or
JWST science program.  The materials presented here will guide readers through the
step-by-step process of designing a science program using the ETC and APT

The HST ETC calculates SNR or Exposure Time for a simulated astronomical observation using one of the instruments on HST. The simulated observation is created using an input web page that is unique to every combination of HST instrument and mode.

The JWST ETC calculates the detailed performance of the instrument and mode by modeling astronomical scenes consisting of single or multiple point and extended sources through multiple workbooks. The  workbook allows user to define sources, place them in scenes, and use the scenes in calculations. Each calculation is unique to a specific JWST instrument and mode. 

The results of the ETC calculations for both HST and JWST are used to determine the input exposure parameters to the Astronomer’s Proposal Tool (APT).

(The contents below are from jwst_etc_apt.html. Move them to this common index.html. Please check if any of the information below is not true for HST APT)
The Astronomer’s Proposal Tool (APT) is an integrated software package for constructing, validating and submitting proposals for the Hubble Space Telescope and
James Webb Space Telescope. Observers must create and submit proposals that are accurate, feasible and schedulable. The software used
to schedule and execute observations can interpret the proposal information only if it is in the proper format. APT is a graphical user interface (GUI) that provides a collection of tools that the observer must use to create a program in this format.

Both program types (HST and JWST) can be created with APT.  An APT program for HST has two modes corresponding with the two-phase proposal process. An APT program for JWST, on the other hand, accommodates a single-phase (single-stream) program process for
most observing modes.  For HST, the purpose of a Phase I program submission is to make the case for the science to be done. In a Phase II program (which applies only to accepted proposals) the observer specifies
details of the observations. Once an instrument and observing mode (or template) are selected in APT, the specific parameters that need to be specified for that
mode are presented to the user. Users specify exposure parameters (determined using the ETC) that provide the necessary signal-to-noise for their science goals.
Using a set of rules and assumed overhead times, APT calculates the total science exposure time being requested in the observations.

The HST and JWST versions of APT are very similar: e.g. there are templates
for each mode, and each template has a set of parameters offering a set of values selected by the user. HST exposure times are in units of orbits, and JWST are in units
of seconds.  Additional differences between the two are highlighted in JWST APT Overview article in JDox (https://jwst-docs.stsci.edu/display/JPP/JWST+Astronomers+Proposal+Tool+Overview) and described in the APT overview slides (link).

Proposed changes to jwst_etc_apt.html on my branch:
The intent of JWST APT is to make it straightforward for users to specify complete observations in the initial submission. Once an instrument and observing mode (or template) are selected, the specific parameters that need to be specified for that mode are presented to the user. The APT team has created extensive documentation that can be accessed from the links below.

Helpful links section here. No changes.

Please let me know what you think. Diane is not on GitHub so I will send an e-mail to her to get her feedback.

If everyone is okay with these changes then I have the following suggestions.
I will push the changes to my branch. It will not have conflicts with what @bhbrooks is updating. If @bhbrooks is done updating the material then he can push his changes. If he is still making changes then @jwhite3 can merge my branch with the master. @bhbrooks can then clone the master branch and make his changes. If Diane has additional feedback we can incorporate it later (I can clone the master and make changes or @bhbrooks can make changes along with his changes depending upon when we get her feedback. Since the training has already started I think it's better to have above changes getting incorporated in the master as soon as possible.

I have one comment about the 'HST ETC and APT' section. It starts with 'Science Motivation' which seems abrupt. It would be good to have a very brief introduction saying something like "This is an example of a COS science use case that walks the users through designing a COS program using HST ETC and APT."

**Comment by bhbrooks** [comment]
@dthatte @jwhite3 My updates are ready to go. Let me know when I can push to the branch.

**Comment by dthatte** [comment]
I am okay with @bhbrooks  pushing his changes to my branch. @jwhite3 please review the above proposed changes and let me know if I can push those after @bhbrooks is done pushing his changes.

**Comment by dthatte** [comment]
I see that @wfischer-stsci has some introductory information on [his branch](https://github.com/spacetelescope/training-library/blob/wfischer_hst_etc/source/apt_etc/hst_apt_etc.txt) that can be used on the HST ETC and APT page at the beginning of the hst_apt_etc page before 'Science Motivation'.

**Comment by jwhite3** [comment]
@dthatte This is great! Go ahead and push these changes, and @bhbrooks you can do the same

**Comment by jwhite3** [comment]
In conjunction with adding this intro, we should also rework the APT intro that's given in the JWST APT/ETC document. This would make that section redundant

**Comment by dthatte** [comment]
I already mentioned that in my comment above. See 'Proposed changes to jwst_etc_apt.html on my branch:' in my earlier comment.

**Comment by jwhite3** [comment]
@dthatte I saw! I deleted the comment. Sorry about that, I had missed that bit

**Comment by dthatte** [comment]
Okay! Can you please delete this and above two comments since they are comments on a deleted comments:)
